# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
